version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(threadName)s - %(processName)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: /home/sunwenkun/Developer/workspace/monopoly.git/logs/monopoly.log
loggers:
  monopoly:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: WARNING
  handlers: [console]