version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(threadName)s - %(processName)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler # 按日备份
    level: DEBUG
    formatter: simple
    filename: /logs/monopoly.log
    when: D                  # 按天轮转 ('D' 表示每天, 'H' 表示每小时, 'MIDNIGHT' 表示午夜)
    interval: 1              # 轮转的时间间隔 (与 'when' 配合使用)
    backupCount: 7           # 保留多少个备份文件 (例如，保留最近7天的日志)
    encoding: utf8           # 日志文件编码
loggers:
  monopoly:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: WARNING
  handlers: [console]